bot:
  interval: 0.5

slack:
  channel: "C0AE04305QR"

strategies:
  special_farming:
    target_level: 11
    safe_money: [0, 0, 23, 64, 281, 767, 2341, 6905, 17860, 44475,
                 127086, 319271, 787087, 1918748, 4741373, 9951633,
                 20749180, 41843536, 122266583, 999999999]
  target:
    target_level: 17
    required_money_per_level: [0, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000, 30000, 40000, 50000, 70000, 100000, 150000, 200000]

required_money_per_level: [0, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000, 30000, 40000, 50000, 70000, 100000, 150000, 200000]

special_weapons:
  - "짝짝이 해진 슬리퍼"
  - "천이 찢어진 너덜거리는 우산"
  - "한 짝 없는 외로운 젓가락"
  - "금이 간 단소"
  - "털이 반쯤 빠진 칫솔"
  - "감전 주의보 기타"
  - "땅에 떨어진 3초 룰"
  - "눅눅한 핫도그 조각"
  - "털이 빠진 허술한 빗자루"
  - "깜빡거리는 광선검"
  - "시들고 축 처진 꽃다발"
  - "물이 줄줄 새는 주전자"

automation:
  delays:
    before: 0.3
    after: 0.1
    paste: 0.1
